name: Deploy to FTP

on:
  push:
    branches:
      - main  # Correct branch specification

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy Forked
        uses: ephorize/ftp-deploy-action@v1.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21  # Add this if required by your FTP server
          protocol: ftp  # Ensure the protocol is correct (ftp, ftps, or ftps-legacy)
          local-dir: ./
          server-dir: /public_html/rexinsit/  # If needed
          log-level: verbose  # For more detailed logging
