name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main  # Change this to your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: ./
        with:
          php-version: '8.1'  # Specify the PHP version compatible with your Laravel project
          extensions: mbstring, bcmath, xml, curl, json, zip, fileinfo

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Build assets
        run: |
          npm install
          

      - name: Deploy to FTP
        uses: ncipollo/ftp-deploy@v1.1.0  # Use the latest stable version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public  # Path to the public directory of your Laravel project
          server-dir: /public_html/rexinsit/  # Change this to your target directory on the server
          port: 21  # Default FTP port
          protocol: ftp  # Change to 'ftps' if your server requires secure FTP
          log-level: verbose  # For detailed logging

      
